version: "3.1"
services:
  postgres:
    image: postgres:10.4-alpine
    volumes:
      - postgresdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: web
      POSTGRES_PASSWORD: ""
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"

  redis:
    image: redis:alpine
    ports:
     - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  postgresdata:
    external: false
  redisdata:
    external: false
  elasticsearchdata:
    external: false
